#!/usr/bin/env sh

cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-name digitrek \
             --out-dir wasm \
             --target web target/wasm32-unknown-unknown/release/digitrek.wasm
cp -r ./assets ./wasm/
