#!/usr/bin/env sh

generate() {
    csound -o "assets/$1.wav" "assets/$1.csd" && \
    ffmpeg -y -i "assets/$1.wav" -acodec libvorbis -map_metadata -1 -fflags +bitexact "assets/$1.ogg" && \
    rm "assets/$1.wav" && \
    afplay "assets/$1.ogg"
}

if [ "$1" = "all" ]; then
    for csd in assets/*.csd; do
        name="${csd#assets/}"
        name="${name%.csd}"
        generate "$name"
    done
else
    generate "$1"
fi
