#!/usr/bin/env sh

if [[ "$1" == "alter" ]]; then
    ffmpeg -i "$2" -filter:a "volume=${4}dB" "$3"
elif [[ "$1" == "normalize" ]]; then
    ffmpeg -i "$2" -filter:a "dynaudnorm=f=150:g=5" "$3"
elif [[ "$1" == "analyze" ]]; then
    ffmpeg -i "$2" -af volumedetect -f null /dev/null
elif [[ "$1" == "convert" ]]; then
    ffmpeg -i "$2" -acodec libvorbis "$3"
else
    echo "invalid input"
    exit 1
fi
