# SPDX-License-Identifier: MIT

name: deploy to github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --locked

      - name: build
        run: |
          ./build_wasm

      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './wasm'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
